### ISSUE TITLE
Repository umbenennen

### ISSUE THREAD

**Issue by lutzbox** [unilinksproject/unilinks#1]
Ich überlege ob wir das Repository eher `web` nennen, dann haben wir einen konsistenten Link für die landing page statt `https://unilinksproject.github.io/unilinks` eher `https://unilinksproject.github.io/web` da wir ja bis auf weiteres keine eigene Domain dafür nehmen werden. das wäre auch konsistent zum `data` Projekt.

**Comment by flueders** [comment]
Man kann die GH-Page so konfigurieren, dass standardmäßig ein bestimmtes repository angezeigt wird.
D.h. https://unilinksproject.github.io/ würde dann direkt auf das unilinks-Repository zeigen

Leider kann ich hier nicht auf die Einstellungen zugreifen, wer ist dafür zuständig?

**Comment by lutzbox** [comment]
@jklmnn Wenn du es nicht schaffst, würde ich das mir die Tage mal anschauen. Unter der Prämisse wäre ich trotzdem dafür das Projekt entsprechend zu benennen!

**Comment by jklmnn** [comment]
@flueders das ist eine gute Idee, denn dann wäre die Frage nach der URL vom Tisch, aber ich hab keine Einstellung dafür gefunden?

@lutzbox ich hatte das Repo unilinks genannt, weil das ja das Hauptprodukt des unilinksprojects ist.  Ich bin dafür, dass wir das Setting das @flueders vorgeschlagen hat nutzen und danach können wir das Repo ohne weitere Probleme umbenennen und verschieben.

**Comment by lutzbox** [comment]
Für was benötigt man jetzt das neue Repo?

**Comment by lutzbox** [comment]
Für was benötigt man jetzt das neue Repo?

**Comment by jklmnn** [comment]
> The source files for User and Organization Pages sites live on the master branch in a dedicated repository named with the GitHub account name:

> To create a User Pages site, name the repository using the naming scheme `<username>.github.io` .
    To create an Organization Pages site, name the repository using the naming scheme `<orgname>.github.io` .

Von https://help.github.com/articles/user-organization-and-project-pages/#user-and-organization-pages-sites

**Comment by jklmnn** [comment]
Achso, du meinst sicher, dass man das auch hätte umbenennen können, ich bin kein Freund vom umbenennen, da hängen dann immer irgendwo noch Referenzen in der Gegend rum...
Jetzt sollte die Seite gehen: https://unilinksproject.github.io

**Comment by lutzbox** [comment]
Okay dann brauchen wir das gh-pages Branch nicht mehr. Dann wäre das unilinks Repository nur der Speicherort des Web Projektes und dient der Entwicklung. Dann würden wir final zur Veröffentlichung in das neue Repository mergen.

**Comment by jklmnn** [comment]
Eigentlich brauchen wir das nicht, wir können ja da auf anderen Branches arbeiten. Ich habe das andere Issue mal in das neue Repo transferiert (GitHub Beta ftw). Wenn wir dieses Issue schließen, sollte das Repo hier obsolet sein.

**Comment by lutzbox** [comment]
Ich würde das unilinks Repo dicht machen. Ich würde auch Branches statt verschiedene Repos bevorzugen.
